name: PayBack
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
targets:
  PayBack:
    type: application
    platform: iOS
    sources:
      - path: iOS/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack
        DEVELOPMENT_TEAM: ""
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: PayBack
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
