name: PayBack
options:
  deploymentTarget:
    iOS: "18.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 11.5.0
settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
targets:
  PayBack:
    type: application
    platform: iOS
    sources:
      - path: iOS/Sources
      - path: iOS/GoogleService-Info.plist
        type: resource
    dependencies:
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseAuth
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack
        DEVELOPMENT_TEAM: ""
        ENABLE_TESTABILITY: YES
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: PayBack
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
  
  PayBackTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PayBackTests
    dependencies:
      - target: PayBack
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBackTests
        DEVELOPMENT_TEAM: ""
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PayBack.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PayBack"
    info:
      path: PayBackTests/Info.plist
    scheme:
      testTargets:
        - name: PayBackTests
          parallelizable: true
          randomExecutionOrder: true
      gatherCoverageData: true
