# ============================================================================
# XcodeGen Project Configuration
# Complete reference with all available fields
# ============================================================================

name: PayBack

# ----------------------------------------------------------------------------
# Project-level Options
# ----------------------------------------------------------------------------
options:
  # Deployment targets for different platforms
  # Minimum iOS 18.0, but compatible with iOS 26+ simulators on Xcode Cloud
  deploymentTarget:
    iOS: "18.0"
    # macOS: "14.0"
    # watchOS: "10.0"
    # tvOS: "18.0"
    # visionOS: "1.0"

  # Bundle ID prefix (optional)
  bundleIdPrefix: com.angansamadder

  # Development region/language
  developmentLanguage: en

  # Use base internationalization
  # usesTabs: false
  # indentWidth: 4
  # tabWidth: 4

  # Create intermediate groups for source folders
  # createIntermediateGroups: true

  # Generate empty directories as groups
  # generateEmptyDirectories: false

  # Default configuration name
  # defaultConfig: Debug

  # Transitively link dependencies
  # transitivelyLinkDependencies: false

  # Automatically generate schemes
  # generateSchemes: true

  # Scheme generation mode: all, none
  # schemeGenerationMode: all

  # Minimize project regeneration
  # minimizeDiffOutput: true

  # Group sorting: name, none
  # groupOrdering:
  #   - pattern: Sources
  #     order: 1

  # File sorting: name, none
  # fileOrdering:
  #   - pattern: "*.swift"
  #     order: 1

# ----------------------------------------------------------------------------
# File Groups (for organizing files in Xcode navigator)
# ----------------------------------------------------------------------------
# fileGroups:
#   - Documentation
#   - Resources

# ----------------------------------------------------------------------------
# Configuration Files (.xcconfig files)
# ----------------------------------------------------------------------------
# configFiles:
#   Debug: Config/Debug.xcconfig
#   Release: Config/Release.xcconfig

# ----------------------------------------------------------------------------
# Include Files (to include other YAML files)
# ----------------------------------------------------------------------------
# include:
#   - path: shared.yml

# ----------------------------------------------------------------------------
# Swift Package Manager Dependencies
# ----------------------------------------------------------------------------
packages:
  Convex:
    url: https://github.com/get-convex/convex-swift
    from: 0.1.0
  Clerk:
    url: https://github.com/clerk/clerk-ios
    from: 0.1.0

# ----------------------------------------------------------------------------
# Project-wide Build Settings
# ----------------------------------------------------------------------------
settings:
  base:
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 6
    DEVELOPMENT_TEAM: "39YTAJZTZ6"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    # VERSIONING_SYSTEM: apple-generic
    # ConvexMobile XCFramework only ships arm64 simulator slices.
    # Exclude x86_64 to prevent linker failures on Intel runners / Rosetta.
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64

  # Configuration-specific settings
  configs:
    Debug:
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    Release:
      GCC_OPTIMIZATION_LEVEL: s
      SWIFT_OPTIMIZATION_LEVEL: -O
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

# ----------------------------------------------------------------------------
# Build Configurations
# ----------------------------------------------------------------------------
# configs:
#   Debug: debug
#   Release: release
#   Staging: debug
#   Production: release

# ----------------------------------------------------------------------------
# Aggregate Targets (for running scripts, dependencies)
# ----------------------------------------------------------------------------
# aggregateTargets:
#   BuildTools:
#     targets:
#       - PayBack
#     buildScripts:
#       - script: echo "Building tools"
#         name: Build Tools

# ----------------------------------------------------------------------------
# Scheme Templates (for reusable scheme configurations)
# ----------------------------------------------------------------------------
# schemeTemplates:
#   AppScheme:
#     build:
#       targets:
#         App: all
#     run:
#       config: Debug
#     test:
#       config: Debug
#       gatherCoverageData: true
#     profile:
#       config: Release
#     analyze:
#       config: Debug
#     archive:
#       config: Release

# ----------------------------------------------------------------------------
# Schemes (build schemes for the project)
# ----------------------------------------------------------------------------
schemes:
  PayBack:
    build:
      targets:
        PayBack: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      testPlans:
        - path: apps/ios/PayBack/TestPlans/PayBack.xctestplan
          default: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  PayBackCITests:
    build:
      targets:
        PayBackCI: all
        PayBackCITests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - PayBackCITests

# ----------------------------------------------------------------------------
# Targets
# ----------------------------------------------------------------------------
targets:
  # --------------------------------------------------------------------------
  # Main Application Target
  # --------------------------------------------------------------------------
  PayBack:
    type: application
    platform: iOS

    # Product name
    productName: "PayBack"

    # Deployment target (overrides project-level)
    # deploymentTarget: "18.0"

    # Sources to include
    sources:
      - path: apps/ios/PayBack/Sources
        # name: Sources
        # type: folder
        # excludes:
        #   - "**/*.md"
        # includes:
        #   - "**/*.swift"
        # group: App
        # createIntermediateGroups: true
        # buildPhase: sources
        # compilerFlags: []
        # resourceTags: []
        # attributes: []

      - path: apps/ios/PayBack/Assets.xcassets
        type: resource

    # Dependencies
    dependencies:
      - package: Convex
        product: ConvexMobile
      - package: Clerk
        product: Clerk

      # Other dependency types:

      # Framework (system)
      # - framework: UIKit.framework
      #   link: true
      #   embed: false

      # SDK (tbd)
      # - sdk: CloudKit.framework

      # Target dependency
      # - target: SharedFramework
      #   link: true
      #   embed: true

      # Carthage
      # - carthage: Alamofire
      #   linkType: dynamic

      # CocoaPods
      # - pod: AFNetworking

      # Pre/Post build scripts
    preBuildScripts:
      - name: Convex Backend Sync
        basedOnDependencyAnalysis: true
        inputFiles:
          - $(SRCROOT)/apps/backend/convex/schema.ts
          - $(SRCROOT)/apps/backend/convex/auth.config.ts
          - $(SRCROOT)/apps/backend/convex/expenses.ts
          - $(SRCROOT)/apps/backend/convex/friends.ts
          - $(SRCROOT)/apps/backend/convex/groups.ts
          - $(SRCROOT)/apps/backend/convex/inviteTokens.ts
          - $(SRCROOT)/apps/backend/convex/linkRequests.ts
          - $(SRCROOT)/apps/backend/convex/users.ts
        outputFiles:
          - $(DERIVED_FILE_DIR)/convex_sync_timestamp
        script: |
          set -euo pipefail

          # Safety check: only deploy when explicitly enabled
          if [ "${CONVEX_DEPLOY_ON_CI:-}" != "1" ]; then
            echo "Convex deploy disabled (CONVEX_DEPLOY_ON_CI != 1). Skipping."
            touch "$DERIVED_FILE_DIR/convex_sync_timestamp"
            exit 0
          fi

          # Verify deploy key is available
          if [ -z "${CONVEX_DEPLOY_KEY:-}" ]; then
            echo "warning: CONVEX_DEPLOY_KEY not set. Skipping Convex deploy."
            touch "$DERIVED_FILE_DIR/convex_sync_timestamp"
            exit 0
          fi

          export PATH="$PATH:/opt/homebrew/bin:/usr/local/bin"

          # Try to find bunx/npx via nvm (local dev) or Homebrew (XcodeCloud)
          export NVM_DIR="$HOME/.nvm"
          if [ -s "$NVM_DIR/nvm.sh" ]; then
            . "$NVM_DIR/nvm.sh"
          elif [ -d "$NVM_DIR/versions/node" ]; then
            LATEST_NODE=$(ls -rd "$NVM_DIR/versions/node"/v* 2>/dev/null | head -n 1)
            if [ -n "$LATEST_NODE" ]; then
              export PATH="$LATEST_NODE/bin:$PATH"
            fi
          fi

          if command -v bunx >/dev/null 2>&1; then
            echo "Deploying Convex backend..."
            bunx convex deploy -y --cmd 'echo "Backend deploy successful"'
            touch "$DERIVED_FILE_DIR/convex_sync_timestamp"
          elif command -v npx >/dev/null 2>&1; then
            echo "Deploying Convex backend..."
            npx convex deploy -y --cmd 'echo \"Backend deploy successful\"'
            touch "$DERIVED_FILE_DIR/convex_sync_timestamp"
          else
            echo "error: bunx and npx not found in PATH. Cannot deploy Convex backend."
            echo "PATH: $PATH"
            exit 1
          fi

    # Build settings
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack
        ENABLE_TESTABILITY: YES
        CODE_SIGN_STYLE: Automatic
        # Use a reduced entitlements file on the simulator.
        # iOS 26 simulators can deny launch when associated domains are present.
        CODE_SIGN_ENTITLEMENTS[sdk=iphonesimulator*]: apps/ios/PayBack/PayBack-Simulator.entitlements
        # CODE_SIGN_IDENTITY: "Apple Development"
        # PROVISIONING_PROFILE_SPECIFIER: ""
        TARGETED_DEVICE_FAMILY: "1" # 1=iPhone, 2=iPad
        # SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        # INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        # INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        # SWIFT_EMIT_LOC_STRINGS: YES
        # ENABLE_PREVIEWS: YES
        # SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        # GCC_PREPROCESSOR_DEFINITIONS: "DEBUG=1"

      # configs:
      #   Debug:
      #     SWIFT_OPTIMIZATION_LEVEL: -Onone
      #     SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      #   Release:
      #     SWIFT_OPTIMIZATION_LEVEL: -O
      #     SWIFT_COMPILATION_MODE: wholemodule

    # Pre/Post build scripts
    # preBuildScripts:

    # Info.plist configuration
    info:
      path: apps/ios/PayBack/Info.plist
      properties:
        CFBundleDisplayName: PayBack
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.finance
        # LSRequiresIPhoneOS: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.angansamadder.PayBack
            CFBundleURLSchemes:
              - payback
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          # - UIInterfaceOrientationLandscapeLeft
          # - UIInterfaceOrientationLandscapeRight
        # UIRequiresFullScreen: false
        # UIStatusBarHidden: false
        # UIViewControllerBasedStatusBarAppearance: true
        # UIApplicationSceneManifest:
        #   UIApplicationSupportsMultipleScenes: false
        #   UISceneConfigurations:
        #     UIWindowSceneSessionRoleApplication:
        #       - UISceneConfigurationName: Default Configuration
        #         UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        # NSCameraUsageDescription: "We need camera access"
        # NSPhotoLibraryUsageDescription: "We need photo library access"
        # NSLocationWhenInUseUsageDescription: "We need location access"
        # UIApplicationSupportsIndirectInputEvents: true
        # ITSAppUsesNonExemptEncryption: false

    # Entitlements
    entitlements:
      path: apps/ios/PayBack/PayBack.entitlements
      properties:
        com.apple.developer.associated-domains:
          - webcredentials:accurate-eagle-80.clerk.accounts.dev

    # Scheme (target-specific)
    # scheme:
    #   environmentVariables:
    #     - variable: OS_ACTIVITY_MODE
    #       value: disable
    #       isEnabled: true
    #   commandLineArguments:
    #     "-com.apple.CoreData.SQLDebug": 1
    #   testTargets:
    #     - name: PayBackTests
    #       parallelizable: true
    #       randomExecutionOrder: true
    #   gatherCoverageData: true

    # Legacy target attributes
    # attributes:
    #   ProvisioningStyle: Automatic
    #   DevelopmentTeam: YOUR_TEAM_ID

    # Templates to inherit from
    # templates:
    #   - BaseApp

  # --------------------------------------------------------------------------
  # Unit Test Target
  # --------------------------------------------------------------------------
  PayBackTests:
    type: bundle.unit-test
    platform: iOS

    # Test target type
    # type: bundle.unit-test     # Unit tests
    # type: bundle.ui-testing    # UI tests

    sources:
      - path: apps/ios/PayBack/Tests

    dependencies:
      - target: PayBack
        # embed: false
        # link: true

      # Additional test frameworks
      # - package: SnapshotTesting
      #   product: SnapshotTesting

    # Test-specific scripts
    # preBuildScripts:
    #   - script: echo "Preparing test environment"
    #     name: Prepare Tests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBackTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PayBack.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PayBack"
        # BUNDLE_LOADER: $(TEST_HOST)
        # ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        # CLANG_ENABLE_MODULES: YES
        # LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks @loader_path/Frameworks"

    info:
      path: apps/ios/PayBack/Tests/Info.plist
      # properties:
      #   CFBundleDevelopmentRegion: en

    scheme:
      testPlans:
        - path: apps/ios/PayBack/TestPlans/PayBack.xctestplan
          default: true
      gatherCoverageData: true
      # coverageTargets:
      #   - PayBack
      # commandLineArguments:
      #   "-FIRDebugEnabled": ""
      # environmentVariables:
      #   - variable: FIRESTORE_EMULATOR_HOST
      #     value: localhost:8080
      #     isEnabled: true
      # language: en
      # region: US
      # disableMainThreadChecker: false
      # stopOnEveryMainThreadCheckerIssue: false

  # --------------------------------------------------------------------------
  # CI App Target (no ConvexMobile)
  # --------------------------------------------------------------------------
  PayBackCI:
    type: application
    platform: iOS

    sources:
      - path: apps/ios/PayBack/Sources
      - path: apps/ios/PayBack/Assets.xcassets
        type: resource

    dependencies:
      - package: Clerk
        product: Clerk

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBackCI
        PRODUCT_MODULE_NAME: PayBack
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) PAYBACK_CI_NO_CONVEX"
        SUPPORTS_MACCATALYST: YES
        "EXCLUDED_ARCHS[sdk=iphonesimulator*]": ""

    info:
      path: apps/ios/PayBack/Info.CI.plist
      properties:
        CFBundleDisplayName: PayBackCI
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)

  # --------------------------------------------------------------------------
  # CI Unit Tests Target (builds against PayBackCI)
  # --------------------------------------------------------------------------
  PayBackCITests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: apps/ios/PayBack/Tests
        excludes:
          - "Services/ConvexAccountServiceTests.swift"
          - "Services/ConvexExpenseServiceTests.swift"
          - "Services/ConvexClientWrapperTests.swift"
          - "Services/ConvexArgumentBuilderTests.swift"
          - "Services/DependenciesTests.swift"
          - "Services/DependenciesExtendedTests.swift"
          - "Services/ClerkAuthProviderTests.swift"
          - "Services/ClerkAuthProviderExtendedTests.swift"

    dependencies:
      - target: PayBackCI

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBackCITests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PayBackCI.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PayBackCI"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) PAYBACK_CI_NO_CONVEX"
        "EXCLUDED_ARCHS[sdk=iphonesimulator*]": ""
# ----------------------------------------------------------------------------
# Additional Target Types Examples
# ----------------------------------------------------------------------------

# Framework Target
# MyFramework:
#   type: framework
#   platform: iOS
#   sources:
#     - path: Framework/Sources
#   info:
#     path: Framework/Info.plist
#     properties:
#       CFBundleShortVersionString: "1.0"
#   settings:
#     base:
#       PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.MyFramework
#       DEFINES_MODULE: YES
#       SKIP_INSTALL: YES

# Static Library Target
# MyStaticLib:
#   type: library.static
#   platform: iOS
#   sources:
#     - path: StaticLib/Sources

# App Extension Target
# NotificationExtension:
#   type: app-extension
#   platform: iOS
#   sources:
#     - path: NotificationExtension
#   dependencies:
#     - target: PayBack
#   settings:
#     base:
#       PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack.NotificationExtension
#   info:
#     path: NotificationExtension/Info.plist
#     properties:
#       NSExtension:
#         NSExtensionPointIdentifier: com.apple.usernotifications.service
#         NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).NotificationService

# Watch App Target
# PayBackWatch:
#   type: watch2-app
#   platform: watchOS
#   sources:
#     - path: WatchApp
#   dependencies:
#     - target: PayBack
#   settings:
#     base:
#       PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack.watchkitapp
#       ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

# Today Extension
# TodayExtension:
#   type: app-extension
#   platform: iOS
#   sources:
#     - path: TodayExtension
#   settings:
#     base:
#       PRODUCT_BUNDLE_IDENTIFIER: com.angansamadder.PayBack.TodayExtension
#   info:
#     properties:
#       NSExtension:
#         NSExtensionPointIdentifier: com.apple.widget-extension
#         NSExtensionMainStoryboard: MainInterface

# ============================================================================
# End of XcodeGen Configuration
# ============================================================================
