excluded:
  - PayBack/Tests
  - Tests

disabled_rules:
  - blanket_disable_command
  - superfluous_disable_command
  - todo
  - trailing_newline
  - identifier_name
  - file_length
  - type_body_length
  - function_body_length
  - large_tuple
  - line_length

line_length:
  warning: 200
  error: 300

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 500
  error: 700
