excluded:
  - PayBack/Tests

disabled_rules:
  - blanket_disable_command

line_length:
  warning: 200
  error: 300

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 400
  error: 600
