disabled_rules:
  - blanket_disable_command
  - superfluous_disable_command
  - todo
  - trailing_newline
  - identifier_name
  - file_length
  - type_body_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - force_try
  - leading_whitespace
  - implicit_optional_initialization
  - vertical_whitespace
  - non_optional_string_data_conversion
  - redundant_discardable_let
  - trailing_comma
  - for_where
  - inclusive_language
  - unneeded_override
  - colon
  - unused_closure_parameter
  - empty_enum_arguments
  - multiple_closures_with_trailing_closure
  - comma
  - cyclomatic_complexity
  - unused_enumerated

excluded:
  - PayBack/Tests
